[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/api/index.js"
  status = 200

[build.environment]
  NODE_ENV = "production"
